### ISSUE TITLE
Anchor links do not work

### ISSUE THREAD

**Issue by EdoPlantinga** [minvws/nl-covid19-notification-app-community-website#10]
@bwbroersma when I click on a hyperlink in the lists in the Praat mee block, they take me to the top of the page. Should those even be links? We can't deeplink to Slack anyway, or at least for me it never works in Slack.

**Comment by bwbroersma** [comment]
This is because almost all links are `"#"` now, the quotes are needed because the `#` would start a yml comment. For me, Slack links (like [#notificatie-app](https://codefornl.slack.com/archives/C011R4NCFMJ)) are working, but you will need to sign in (without an option to register). So the Slack button should link to https://praatmee.codefor.nl/

**Comment by arianvp** [comment]
Fixed https://github.com/minvws/nl-covid19-notification-app-community-website/commit/b2e7a180dcfcc36777f08b5f37a1aa9c471325e5

**Comment by EdoPlantinga** [comment]
Sorry @bwbroersma , I was not paying attention, didn't notice the empty #'s
